name: Build and deploy Python project to Azure Function App - datavizapp-py-functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './backend/datavizapp-py-functions'
  PYTHON_VERSION: '3.12'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 'Deploy to Azure Functions using Oryx'
        uses: Azure/functions-action@v1
        with:
          app-name: 'datavizapp-py-functions'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
